services:
  server-logiflowerp-webhook:
    image: logiflowerp/server-logiflowerp-webhook:latest
    env_file:
     - ./.env
    environment:
      NODE_ENV: production
    volumes:
      - /home/scripts:/scripts
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true